### ISSUE TITLE
Request exception without response.

### ISSUE THREAD

**Issue by My1** [clef/instant2fa-php#2]
in Line 86 of Instant2FA.php I get an error where it seems it cant really find a message.
upon some digging I found out that curl on My XAMPP test server doesnt get the CA list, and (seemingly this hasnt been a problem when using clef because it uses file_get_contents to call the URL, dont ask me why that works but curl not, still investigating)

but putting my server config aside, the Problem is when it cant find a message, the `if` on line 79 wont trigger and therefore doesnt get filled making PHP crash with:

Notice: Undefined variable: response in path\tests\i2f-php\lib\Instant2FA.php on line 86

Fatal error: Call to a member function getBody() on a non-object in path\tests\i2f-php\lib\Instant2FA.php on line 86

so you would need to get out if there is no message for whatever reason.

**Comment by landakram** [comment]
@My1 thanks for the bug report! Looking at this today and should have a fix by the end of the day

**Comment by landakram** [comment]
Fixed in https://github.com/clef/instant2fa-php/pull/3
